version: '2.3'

services:
  redis-server:
    restart: always
    image: redis:4.0
    platform: "linux/amd64"
    container_name: redis-server
    command: /bin/bash -c 'redis-server --requirepass yourpassword --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    mem_limit: 96m

  redis-insight:
    image: redislabs/redisinsight:latest
    platform: "linux/amd64"
    container_name: redis-insight
    ports:
      - "8001:8001"
    depends_on:
      - redis-server
      
  mysql-server:
    restart: always
    image: mysql:5.7
    container_name: mysql-server
    platform: "linux/amd64"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    mem_limit: 512m

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
