version: '2.3'

services:
  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --requirepass yourpassword --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    mem_limit: 96m

volumes:
  redis-data:
    driver: local
